version: '3.8'

services:
  bind:
    image: ubuntu/bind9:9.16-21.10_beta
    ports:
    - "53:53/udp"
    - "53:53/tcp"
    - "10000:10000/tcp"
    volumes:
    - ./services/bind9/named.conf:/etc/bind/named.conf
    - ./services/bind9/ru.cdn.rascal.su:/etc/bind/master/ru.cdn.rascal.su
    - ./services/bind9/de.cdn.rascal.su:/etc/bind/master/de.cdn.rascal.su
    - ./services/bind9/GeoIP.acl:/etc/bind/geo/GeoIP.acl
    - ./data/bind9/chache:/var/cache/bind
    - ./data/bind9/records:/var/lib/bind

  web1:
    build:
      context: ./services/web
      dockerfile: Dockerfile
    environment:
      FLASK_APP: web.py
      APP_FOLDER: /home/app/web
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    ports:
      - 5000

  web2:
    build:
      context: ./services/web
      dockerfile: Dockerfile
    environment:
      FLASK_APP: web.py
      APP_FOLDER: /home/app/web
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    ports:
      - 5000

  web3:
    build:
      context: ./services/web
      dockerfile: Dockerfile
    environment:
      FLASK_APP: web.py
      APP_FOLDER: /home/app/web
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    ports:
      - 5000

  nginx:
    build: ./services/nginx
    ports:
      - 1337:80
    depends_on:
      - web1
      - web2
      - web3
